#!/bin/bash
echo "ATTENTION : il faut que le fichier SimulateurTest.java ait été compilé !"
java -cp ./src/junit-4.12.jar:./src/hamcrest-core-1.3.jar:./bin:. org.junit.runner.JUnitCore SimulateurTest
